#DB configuration
# yml 是以K-V的格式 用“:”分割  且每个":"后都要有一个空格  不然报错
spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/boot
      username: root
      password: tiger
loging:
  level:
      com.itheima.springboot: debug